# Generated by Django 2.2.7 on 2020-03-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=256, null=True, verbose_name='Website')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Type')),
                ('star', models.CharField(blank=True, max_length=256, null=True, verbose_name='Star')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('location', models.CharField(blank=True, max_length=256, null=True, verbose_name='Location')),
                ('state', models.CharField(blank=True, max_length=256, null=True, verbose_name='State')),
                ('zipCode', models.CharField(blank=True, max_length=256, null=True, verbose_name='ZipCode')),
                ('lat', models.CharField(blank=True, max_length=256, null=True, verbose_name='Lat')),
                ('lon', models.CharField(blank=True, max_length=256, null=True, verbose_name='Lon')),
                ('lowestRoomPrice', models.CharField(blank=True, max_length=256, null=True, verbose_name='LowestRoomPrice')),
            ],
        ),
    ]
