# Generated by Django 2.2.7 on 2020-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='page',
        ),
        migrations.AddField(
            model_name='panel',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort'),
        ),
    ]
