# Generated by Django 2.2.7 on 2020-03-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20200328_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.CharField(blank=True, max_length=256, null=True, verbose_name='publish')),
                ('source', models.CharField(blank=True, max_length=256, null=True, verbose_name='publish')),
                ('postDate', models.CharField(blank=True, max_length=256, null=True, verbose_name='postDate')),
                ('weekday', models.CharField(blank=True, max_length=256, null=True, verbose_name='weekday')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='title')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='content')),
                ('location', models.CharField(blank=True, max_length=256, null=True, verbose_name='location')),
                ('state', models.CharField(blank=True, max_length=256, null=True, verbose_name='state')),
                ('case', models.CharField(blank=True, max_length=256, null=True, verbose_name='case')),
                ('criminals', models.CharField(blank=True, max_length=256, null=True, verbose_name='criminals')),
                ('race', models.CharField(blank=True, max_length=256, null=True, verbose_name='race')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='url')),
            ],
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ('sort',), 'verbose_name': 'Panel', 'verbose_name_plural': 'Panel'},
        ),
    ]
