# Generated by Django 2.2.7 on 2020-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20200329_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='lowestRoomPrice',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='star',
        ),
        migrations.AddField(
            model_name='hotel',
            name='risk',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Risk'),
        ),
    ]
